apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../components
- ../../components/frontend
patchesStrategicMerge:
- use_dev_images.yaml
patchesJson6902:
- path: use_loadbalancer_traefik_service.yaml
  target:
    version: v1
    kind: Service
    name: eventual-hub-proxy-external
secretGenerator:
- name: eventual-hub
  envs:
  - .env.dev-auth0.secret