version: 2
updates:
- package-ecosystem: pip
  directory: /
  schedule:
    interval: weekly
    # Add assignees
  assignees:
  - samster25
  - jaychia

- package-ecosystem: cargo
  directory: /
  schedule:
    interval: weekly
    # Add assignees
  assignees:
  - samster25
  - jaychia

- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
    # Add assignees
  assignees:
  - samster25
  - jaychia
