[dependencies]
common-error = {path = "../common/error", default-features = false}
daft-arrow = {path = "../daft-arrow"}
daft-core = {path = "../daft-core", default-features = false}
daft-dsl = {path = "../daft-dsl", default-features = false}
serde = {workspace = true}
typetag = {workspace = true}

[features]
python = [
  "common-error/python",
  "daft-core/python",
  "daft-dsl/python"
]

[lints]
workspace = true

[package]
name = "daft-functions-serde"
edition.workspace = true
