[dependencies]
arrow = {workspace = true, features = ["ffi"]}
arrow-schema = {workspace = true}
daft-arrow = {path = "../../daft-arrow"}
pyo3 = {workspace = true}

[lints]
workspace = true

[package]
edition = {workspace = true}
name = "common-arrow-ffi"
version = {workspace = true}
