[dependencies]
arrow = {version = "54.2.1", features = ["ffi"]}
arrow-schema = {version = "54.2.1"}
daft-arrow = {path = "../../daft-arrow"}
pyo3 = {workspace = true, optional = true}

[features]
python = ["dep:pyo3"]

[lints]
workspace = true

[package]
edition = {workspace = true}
name = "common-arrow-ffi"
version = {workspace = true}
