[dependencies]
pyo3 = {workspace = true, optional = true}
sysinfo = "0.32.0"

[features]
python = ["dep:pyo3"]

[lints]
workspace = true

[package]
edition = {workspace = true}
name = "common-system-info"
version = {workspace = true}
