[dependencies]
common-error = {path = "../common/error", default-features = false}
common-io-config = {path = "../common/io-config", default-features = false}
common-py-serde = {path = "../common/py-serde", default-features = false}
common-resource-request = {path = "../common/resource-request", default-features = false}
common-scan-info = {path = "../common/scan-info", default-features = false}
common-treenode = {path = "../common/treenode", default-features = false}
daft-core = {path = "../daft-core", default-features = false}
daft-dsl = {path = "../daft-dsl", default-features = false}
daft-logical-plan = {path = "../daft-logical-plan", default-features = false}
log = {workspace = true}
pyo3 = {workspace = true, optional = true}
serde = {workspace = true}
strum = {version = "0.27", features = ["derive"]}
indexmap = {workspace = true}
daft-functions = {path = "../daft-functions", default-features = false}
daft-functions-list = {path = "../daft-functions-list", default-features = false}

[features]
python = [
  "dep:pyo3",
  "common-error/python",
  "common-resource-request/python",
  "common-scan-info/python",
  "common-py-serde/python",
  "daft-core/python",
  "daft-dsl/python",
  "daft-logical-plan/python"
]

[lints]
workspace = true

[package]
edition = {workspace = true}
name = "daft-local-plan"
version = {workspace = true}
