[dependencies]
async-stream = {version = "0.3.3", optional = true}
brotli = {version = "^3.3", optional = true}
flate2 = {version = "^1.0", optional = true, default-features = false}
futures = {version = "0.3", optional = true}
lz4 = {version = "1.24", optional = true}
lz4_flex = {version = "^0.9", optional = true}
parquet-format-safe = "0.2"
seq-macro = {version = "0.3", default-features = false}
serde = {version = "^1.0", features = ["derive"]}
snap = {version = "^1.1", optional = true}
streaming-decompression = "0.1"
xxhash-rust = {version = "0.8", optional = true, features = ["xxh64"]}
zstd = {version = "^0.12", optional = true, default-features = false}

[dev-dependencies]
criterion = "0.4"
rand = "0.8"
tokio = {version = "1", features = ["macros", "rt"]}

[features]
async = ["async-stream", "futures", "parquet-format-safe/async"]
bloom_filter = ["xxhash-rust"]
default = ["snappy", "gzip", "lz4", "zstd", "brotli", "bloom_filter"]
full = ["snappy", "gzip", "lz4", "zstd", "brotli", "bloom_filter", "async"]
gzip = ["flate2/rust_backend"]
gzip_zlib_ng = ["flate2/zlib-ng"]
snappy = ["snap"]

[lib]
bench = false
name = "parquet2"

[package]
authors = [
  "Jorge C. Leitao <jorgecarleitao@gmail.com",
  "Apache Arrow <dev@arrow.apache.org>"
]
description = "Safe implementation of parquet IO."
edition = "2021"
homepage = "https://github.com/jorgecarleitao/parquet2"
keywords = ["analytics", "parquet"]
license = "Apache-2.0"
name = "parquet2"
readme = "README.md"
repository = "https://github.com/jorgecarleitao/parquet2"
version = "0.17.2"

[package.metadata.cargo-machete]
ignored = ["criterion", "rand", "tokio"]

[package.metadata.docs.rs]
features = ["full"]
rustdoc-args = ["--cfg", "docsrs"]
