apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deploy.yaml
- svc.yaml
- ingress.yaml
- ca.yaml
- cert.yaml
- rbac.yaml
configMapGenerator:
  - name: kuberay-client-config
    files:
      - kuberay-client-config.yaml
