[dependencies]
common-daft-config = {path = "../common/daft-config", default-features = false}
common-error = {path = "../common/error", default-features = false}
common-io-config = {path = "../common/io-config", default-features = false}
daft-core = {path = "../daft-core", default-features = false}
daft-dsl = {path = "../daft-dsl", default-features = false}
daft-plan = {path = "../daft-plan", default-features = false}
daft-scan = {path = "../daft-scan", default-features = false}
pyo3 = {workspace = true, optional = true}
serde = {workspace = true, features = ["rc"]}

[dev-dependencies]
rstest = {workspace = true}

[features]
python = ["dep:pyo3", "common-error/python", "common-io-config/python", "common-daft-config/python", "daft-core/python", "daft-plan/python", "daft-dsl/python"]

[package]
edition = {workspace = true}
name = "daft-scheduler"
version = {workspace = true}

[package.metadata.cargo-machete]
ignored = ["rstest"]
