global:
  scrape_interval: 5s
  scrape_timeout: 3s
  evaluation_interval: 30s

scrape_configs:
- job_name: 'daft'
  static_configs:
  - targets: ['collector:9464']

storage:
  tsdb:
    out_of_order_time_window: 30m
