[dependencies]
arrow2 = {workspace = true}
common-error = {path = "../common/error", default-features = false}
daft-core = {path = "../daft-core", default-features = false}
log = {workspace = true}
num-traits = "0.2.19"
pyo3 = {workspace = true, optional = true}
base64.workspace = true

[dependencies.image]
default-features = false
features = ["gif", "jpeg", "ico", "png", "tiff", "webp", "bmp", "hdr"]
version = "0.25.4"

[features]
python = [
  "dep:pyo3",
  "common-error/python"
]

[lints]
workspace = true

[package]
name = "daft-image"
edition.workspace = true
version.workspace = true
