[dependencies]
arrow-schema = {version = "57.1.0"}
daft-arrow = {path = "../../daft-arrow"}
pyo3 = {workspace = true, optional = true}
regex = {workspace = true}
serde_json = {workspace = true}
thiserror = {workspace = true}

[dev-dependencies]
parquet2 = {workspace = true}

[features]
python = ["dep:pyo3"]

[lints]
workspace = true

[package]
edition = {workspace = true}
name = "common-error"
version = {workspace = true}
