[dependencies]
arrow2 = {workspace = true}
pyo3 = {workspace = true, optional = true}
serde_json = {workspace = true}

[features]
default = ["python"]
python = ["dep:pyo3"]

[package]
edition = {workspace = true}
name = "common_error"
version = {workspace = true}
