[dependencies]
proc-macro-crate = "3.4"
proc-macro-error = "1.0"
proc-macro2 = "1.0"
quote = "1.0"
syn = "2.0"

[lib]
proc-macro = true

[package]
edition = {workspace = true}
name = "common-macros"
version = {workspace = true}
