[dependencies]
common-error = {path = "../error", default-features = false}
common-ndarray = {workspace = true}
daft-schema = {path = "../../daft-schema", default-features = false}
image = {workspace = true, features = [
  "gif",
  "jpeg",
  "ico",
  "png",
  "tiff",
  "webp",
  "bmp",
  "hdr"
]}
ndarray = {workspace = true}
pyo3 = {workspace = true, optional = true}
serde = {workspace = true}

[dev-dependencies]
bincode = {workspace = true, features = ["serde"]}

[features]
python = ["dep:pyo3"]

[lints]
workspace = true

[package]
edition = {workspace = true}
name = "common-image"
version = {workspace = true}
