[dependencies]
arrow-array = {workspace = true}
arrow-schema = {workspace = true}
common-error = {path = "../common/error", default-features = false}
serde_arrow = {version = "0.13.7", features = ["arrow-57"]}
sketches-ddsketch = {workspace = true}
snafu = {workspace = true}

[lints]
workspace = true

[package]
edition = {workspace = true}
name = "daft-sketch"
version = {workspace = true}
