[dependencies]
arrow-array = {workspace = true}
arrow-schema = {workspace = true}
common-error = {path = "../common/error", default-features = false}
serde_arrow = {version = "0.12.3", features = ["arrow-54"]}
sketches-ddsketch = {workspace = true}
snafu = {workspace = true}

[lints]
workspace = true

[package]
edition = {workspace = true}
name = "daft-sketch"
version = {workspace = true}
