[dependencies]
common-py-serde = {path = "../py-serde", default-features = false}
indicatif = "0.17"
serde = {workspace = true}
bincode = {workspace = true}
smallvec = {workspace = true, features = ["serde"]}
pyo3 = {workspace = true, optional = true}
daft-schema = {path = "../../daft-schema", default-features = false}

[features]
python = ["dep:pyo3"]

[lints]
workspace = true

[package]
edition = {workspace = true}
name = "common-metrics"
version = {workspace = true}
