[dependencies]
common-py-serde = {path = "../py-serde", default-features = false}
indicatif = {workspace = true}
serde = {workspace = true}
bincode = {workspace = true}
smallvec = {workspace = true, features = ["serde"]}
pyo3 = {workspace = true, optional = true}
enum_dispatch = "0.3"
itertools = {workspace = true}
opentelemetry = {workspace = true}
atomic_float = "*"

[features]
python = ["dep:pyo3"]

[lints]
workspace = true

[package]
edition = {workspace = true}
name = "common-metrics"
version = {workspace = true}
