[dependencies]
arrow = {workspace = true, features = ["ffi"]}

[lints]
workspace = true

[package]
description = "Daft extension C ABI contract"
edition = {workspace = true}
license = "Apache-2.0"
name = "daft-ext-abi"
version = {workspace = true}
