[dependencies]
bincode = {workspace = true}
common-error = {path = "../common/error", default-features = false}
daft-arrow = {path = "../daft-arrow"}
common-partitioning = {path = "../common/partitioning", default-features = false}
common-runtime = {path = "../common/runtime", default-features = false}
daft-core = {path = "../daft-core", default-features = false}
daft-csv = {path = "../daft-csv", default-features = false}
daft-dsl = {path = "../daft-dsl", default-features = false}
daft-io = {path = "../daft-io", default-features = false}
daft-json = {path = "../daft-json", default-features = false}
daft-parquet = {path = "../daft-parquet", default-features = false}
daft-recordbatch = {path = "../daft-recordbatch", default-features = false}
daft-scan = {path = "../daft-scan", default-features = false}
daft-stats = {path = "../daft-stats", default-features = false}
daft-warc = {path = "../daft-warc", default-features = false}
dashmap = {workspace = true}
futures = {workspace = true}
parquet2 = {workspace = true}
pyo3 = {workspace = true, optional = true}
snafu = {workspace = true}
tokio = {workspace = true}
tracing = {workspace = true}

[features]
python = [
  "dep:pyo3",
  "common-error/python",
  "common-partitioning/python",
  "daft-core/python",
  "daft-dsl/python",
  "daft-recordbatch/python",
  "daft-io/python",
  "daft-parquet/python",
  "daft-scan/python",
  "daft-stats/python",
  "daft-csv/python",
  "daft-json/python"
]

[lints]
workspace = true

[package]
edition = {workspace = true}
name = "daft-micropartition"
version = {workspace = true}
