[workspace]

[package]
name = "range_source"
edition = "2024"
version = "0.1.0"

[lib]
name = "range_source"
crate-type = ["cdylib"]

[dependencies]
daft-ext = {path = "../../src/daft-ext"}
arrow-array = {version = "57.1.0", features = ["chrono-tz"]}
arrow-schema = "57.1.0"
serde_json = "1"
