[dependencies]
bincode = {workspace = true}
common-error = {path = "../common/error", default-features = false}
common-resource-request = {path = "../common/resource-request", default-features = false}
common-scan-info = {path = "../common/scan-info", default-features = false}
daft-core = {path = "../daft-core"}
daft-dsl = {path = "../daft-dsl"}
daft-logical-plan = {path = "../daft-logical-plan"}
daft-proto = {path = "../daft-proto"}
daft-schema = {path = "../daft-schema"}
prost = {workspace = true}
pyo3 = {workspace = true, optional = true}
thiserror = {workspace = true}

[features]
python = ["dep:pyo3"]

[lints]
workspace = true

[package]
name = "daft-ir"
edition.workspace = true
version.workspace = true
