[dependencies]
common-runtime = {path = "../runtime", default-features = false}
dashmap = {workspace = true}
reqwest = {workspace = true}
opentelemetry = {workspace = true}
opentelemetry-otlp = {workspace = true}
opentelemetry_sdk = {workspace = true}
serde = {workspace = true}
serde_json = {workspace = true}
tracing = {workspace = true}
tracing-opentelemetry = {version = "0.32", default-features = false, features = ["metrics"]}
tracing-subscriber = {workspace = true}
log = {workspace = true}

[lints]
workspace = true

[package]
edition = {workspace = true}
name = "common-tracing"
version = {workspace = true}
