[dependencies]
arrow = "54.2.1"
aho-corasick = "1.1.3"
daft-arrow = {path = "../daft-arrow"}
chrono = {workspace = true}
chrono-tz = {workspace = true}
common-error = {path = "../common/error", default-features = false}
daft-core = {path = "../daft-core", default-features = false}
daft-dsl = {path = "../daft-dsl", default-features = false}
itertools = {workspace = true}
num-traits = {workspace = true}
common-pattern = {path = "../common/pattern"}
regex = {workspace = true}
serde = {workspace = true}
typetag = {workspace = true}
unicode-normalization = "0.1.25"
ahash = {workspace = true}

[features]
python = [
  "common-error/python",
  "daft-core/python",
  "daft-dsl/python"
]

[lints]
workspace = true

[package]
name = "daft-functions-utf8"
edition.workspace = true
version.workspace = true
