[dependencies]
arrow2 = {workspace = true}
common-daft-config = {path = "../common/daft-config", default-features = false}
common-display = {path = "../common/display", default-features = false}
common-error = {path = "../common/error", default-features = false}
common-file-formats = {path = "../common/file-formats", default-features = false}
common-io-config = {path = "../common/io-config", default-features = false}
common-py-serde = {path = "../common/py-serde", default-features = false}
common-runtime = {path = "../common/runtime", default-features = false}
common-scan-info = {path = "../common/scan-info", default-features = false}
daft-core = {path = "../daft-core", default-features = false}
daft-csv = {path = "../daft-csv", default-features = false}
daft-decoding = {path = "../daft-decoding", default-features = false}
daft-io = {path = "../daft-io", default-features = false}
daft-json = {path = "../daft-json", default-features = false}
daft-logical-plan = {path = "../daft-logical-plan", default-features = false}
daft-parquet = {path = "../daft-parquet", default-features = false}
daft-schema = {path = "../daft-schema", default-features = false}
daft-stats = {path = "../daft-stats", default-features = false}
daft-table = {path = "../daft-table", default-features = false}
futures = {workspace = true}
indexmap = {workspace = true}
itertools = {workspace = true}
parquet2 = {workspace = true}
pyo3 = {workspace = true, optional = true}
serde = {workspace = true}
snafu = {workspace = true}
typetag = {workspace = true}
urlencoding = "2.1.3"

[features]
python = ["dep:pyo3", "common-error/python", "daft-core/python", "daft-logical-plan/python", "daft-table/python", "daft-stats/python", "common-file-formats/python", "common-io-config/python", "common-daft-config/python", "common-scan-info/python", "daft-schema/python"]

[lints]
workspace = true

[package]
edition = {workspace = true}
name = "daft-scan"
version = {workspace = true}
